services:
  devops-demo:
    image: devops-demo:0.1
    container_name: devops-demo-app
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: appdb
      DB_USER: dbuser
      DB_PASSWORD: dbpass
  db:
    image: postgres:17-alpine3.23
    container_name: postgres-db
    shm_size: 128mb
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: appdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
